name: portfolio-website
services:
- name: web
  source_dir: /
  github:
    repo: JoaoPontes98/portfolio-website
    branch: main
  run_command: npm run serve
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: AWS_REGION
    value: ca-central-1
  - key: FROM_EMAIL
    value: your-verified-ses-email@example.com
  - key: TO_EMAIL
    value: your-personal-email@gmail.com
  - key: AWS_ACCESS_KEY_ID
    value: your-access-key
  - key: AWS_SECRET_ACCESS_KEY
    value: your-secret-key
