server:
  port: 8080

spring:
  application:
    name: portfolio-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: ${DB_USERNAME:portfolio_user}
    password: ${DB_PASSWORD:portfolio_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  

aws:
  ses:
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    from-email: ${FROM_EMAIL:joao.vrpontes@gmail.com}
    to-email: ${TO_EMAIL:joao.vrpontes@gmail.com}

logging:
  level:
    com.portfolio: DEBUG
    org.springframework.web: DEBUG
